<?php

function bots_menu() {  
    $items['bots_view'] = array(
        'page callback' => 'menufun_bots_view',
		'access callback' => 'user_access',
		'access arguments' => array('View bots information'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_data'] = array(
        'page callback' => 'menufun_bots_data',
		'access callback' => 'user_access',
		'access arguments' => array('Access to bots data'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_data_edit'] = array(
        'page callback' => 'menufun_bots_data_edit',
		'access callback' => TRUE,
		//'access arguments' => array('Insert/Update bots data'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_run'] = array(
        'page callback' => 'menufun_bots_run',
		'access callback' => 'user_access',
		'access arguments' => array('Manually run bots'),
        'type' => MENU_CALLBACK,
    );
    $items['bots_dump'] = array(
        'page callback' => 'menufun_bots_dump',
		'access callback' => 'user_access',
		'access arguments' => array('Dump data of bots'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function all_access(){
	return true;
}

function menufun_bots_view()
{
	module_load_include('inc', 'bots', 'inc/bots.view');
	return get_view();
	//exit(0);
}

function menufun_bots_data()
{
	module_load_include('inc', 'bots', 'inc/bots.data');
	echo get_data();
	exit(0);
}

function menufun_bots_data_edit()
{
	module_load_include('inc', 'bots', 'inc/bots.dataedit');
	echo get_data_edit();
	exit(0);
}

function menufun_bots_dump()
{
	module_load_include('inc', 'bots', 'inc/bots.dump');
	//echo get_dump();
	echo '';
	exit(0);
}

/*
  The schema function function bots_schema(){} should be placed in file: bots.install,
  which has not been created here 
*/

